debug_key_name: upp-k8s-provisioning-debug

# Controller Instance Properties
controller_instance_type: c4.large
controller_count: 2

# ETCD Instance Properties
etcd_instance_type: t2.medium
etcd_count: 3

# Worker Instance Properties
worker_pools: 
  - {id: 1, instance_type: m4.xlarge, count: 5, role: worker, subnets: 3}
  - {id: 2, instance_type: t2.medium, count: 3, role: mongo-worker, subnets: 3, dedicatedtaint: mongo}
  - {id: 3, instance_type: m4.large, count: 1, role: kafka-worker, subnets: 1, dedicatedtaint: kafka}

worker_security_groups:
  - sg-f1ec2b82

k8s_version: v1.8.4_coreos.0
tags:
  - {name: ipCode, value: P196}
  - {name: teamDL, value: universal.publishing.platform@ft.com}
  - {name: stopSchedule, value: nostop}
